export const EventTypes = {
    SALE_ADDED: "SALE_ADDED",
    INVENTORY_ADDED: "INVENTORY_ADDED",
    ASSET_ADDED: "ASSET_ADDED",
    ASSET_DISPOSED: "ASSET_DISPOSED",
    EXPENSES_ADDED: "EXPENSES_ADDED",
    LIABILITY_ADDED: "LIABILITY_ADDED",
    LIABILITY_REPAYMENT: "LIABILITY_REPAYMENT"
}

export interface EventType {
    SALE_ADDED: "SALE_ADDED";
    INVENTORY_ADDED: "INVENTORY_ADDED";
    ASSET_ADDED: "ASSET_ADDED";
    ASSET_DISPOSED: "ASSET_DISPOSED";
    EXPENSES_ADDED: "EXPENSES_ADDED";
    LIABILITY_ADDED: "LIABILITY_ADDED";
    LIABILITY_REPAYMENT: "LIABILITY_REPAYMENT";
}