export const EventTypes = {
    SALE_ADDED: "SALE_ADDED",
    INVENTORY_ADDED: "INVENTORY_ADDED",
    INVENTORY_UPDATED: "INVENTORY_UPDATED",
    ASSET_ADDED: "ASSET_ADDED",
    ASSET_DISPOSED: "ASSET_DISPOSED",
    EXPENSES_ADDED: "EXPENSES_ADDED",
    LIABILITY_ADDED: "LIABILITY_ADDED",
    LIABILITY_REPAYMENT: "LIABILITY_REPAYMENT",
    PRODUCT_CREATED: "PRODUCT_CREATED",
    PRODUCT_UPDATED: "PRODUCT_UPDATED",
    PRODUCT_DELETED: "PRODUCT_DELETED", 
}

export interface EventType {
    SALE_ADDED: "SALE_ADDED";
    INVENTORY_UPDATED: "INVENTORY_UPDATED";
    INVENTORY_ADDED: "INVENTORY_ADDED";
    ASSET_ADDED: "ASSET_ADDED";
    ASSET_DISPOSED: "ASSET_DISPOSED";
    EXPENSES_ADDED: "EXPENSES_ADDED";
    LIABILITY_ADDED: "LIABILITY_ADDED";
    LIABILITY_REPAYMENT: "LIABILITY_REPAYMENT";
    PRODUCT_CREATED: "PRODUCT_CREATED";
    PRODUCT_UPDATED: "PRODUCT_UPDATED";
    PRODUCT_DELETED: "PRODUCT_DELETED";
}