export const BusinessEventTypes = {
    BUSINESS_CREATED: "BUSINESS_CREATED",
    BUSINESS_ACTIVATION: "BUSINESS_ACTIVATION",
    BRANCH_CREATED: "BRANCH_CREATED",
    BRANCH_SWITCH: "BRANCH_SWITCH"
}