export const InventoryEventType = {
    PRODUCT_CREATED: "PRODUCT_CREATED",
    PRODUCT_UPDATED: "PRODUCT_UPDATED",
    PRODUCT_DELETED: "PRODUCT_DELETED", 
    INVENTORY_ADDED: "INVENTORY_ADDED",
    INVENTORY_UPDATED: "INVENTORY_UPDATED",
}