export const OpeninigEventType = {
    OPENING_INVENTORY_CREATED: "OPENING_INVENTORY_CREATED",
    OPENING_INVENTORY_UPDATED: "OPENING_INVENTORY_UPDATED",
    OPENING_INVENTORY_DELETED: "OPENING_INVENTORY_UPDATED",
    OPENING_ASSET : "OPENING_ASSET",
    OPENING_LIABILITIES: "OPENING_LIABILITIES",
    OPENING_CASH_ADDED: "OPENING_CASH"
}