import {
    Account,
    LedgerEntry,
} from "@business/shared-types";

import {
    LedgerDirection,
    LedgerEntry as PrismaLedgerEntry,
    Prisma,
} from "../../../infrastructure/postgresql/prisma/generated/client.js";

import { prisma } from "../../../infrastructure/postgresql/prismaClient.js";

import {
    LedgerRepository,
    LedgerAccountTotals,
} from "@business/ledger-engine"


export class LedgerRepositoryImpl
    implements LedgerRepository {


    constructor(
        private readonly db = prisma
    ) {}


    /*
     * ============================================================
     * APPEND
     * ============================================================
     *
     * Ledger entries are idempotent through:
     *
     * eventId + index
     *
     * Therefore use upsert instead of blind create.
     * ============================================================
     */

    async append(
        entries: LedgerEntry[],
        tx: Prisma.TransactionClient = this.db
    ): Promise<void> {

        for (const entry of entries) {

            await tx.ledgerEntry.upsert(

                LedgerMapper.toUpsertArgs(
                    entry
                )

            );

        }

    }


    /*
     * ============================================================
     * GET BY ID
     * ============================================================
     */

    async getById(
        id: string
    ): Promise<LedgerEntry | null> {

        const row =
            await this.db.ledgerEntry.findUnique({

                where: {
                    id,
                },

            });


        return row
            ? LedgerMapper.fromRow(row)
            : null;

    }


    /*
     * ============================================================
     * GET BY EVENT
     *
     * LedgerEntry:
     *
     * eventId + index
     *
     * represents the ordered ledger lines generated by an event.
     * ============================================================
     */

    async getByEvent(
        eventId: string
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    eventId,
                },

                orderBy: {
                    index: "asc",
                },

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET BY BUSINESS
     * ============================================================
     */

    async getByBusiness(
        businessId: string
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    businessId,
                },

                orderBy: [
                    {
                        createdAt: "asc",
                    },
                    {
                        index: "asc",
                    },
                ],

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET BY BRANCH
     * ============================================================
     */

    async getByBranch(
        branchId: string
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    branchId,
                },

                orderBy: [
                    {
                        createdAt: "asc",
                    },
                    {
                        index: "asc",
                    },
                ],

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET BY ACCOUNT
     * ============================================================
     */

    async getByAccount(
        account: Account
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    account:
                        account as Prisma.Account,
                },

                orderBy: {
                    createdAt: "asc",
                },

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET ACCOUNT TOTALS
     * ============================================================
     *
     * We aggregate Decimal values in PostgreSQL through Prisma.
     *
     * Prisma returns Decimal rather than number.
     * ============================================================
     */

    async getAccountTotals(
        businessId: string,
        account: Account
    ): Promise<LedgerAccountTotals> {

        const [
            debitResult,
            creditResult,
        ] = await Promise.all([

            this.db.ledgerEntry.aggregate({

                where: {

                    businessId,

                    account:
                        account as Prisma.Account,

                    direction:
                        LedgerDirection.DEBIT,
                },

                _sum: {
                    amount: true,
                },

            }),


            this.db.ledgerEntry.aggregate({

                where: {

                    businessId,

                    account:
                        account as Prisma.Account,

                    direction:
                        LedgerDirection.CREDIT,
                },

                _sum: {
                    amount: true,
                },

            }),

        ]);


        return {

            totalDebits:
                Number(
                    debitResult._sum.amount ?? 0
                ),

            totalCredits:
                Number(
                    creditResult._sum.amount ?? 0
                ),

        };

    }


    /*
     * ============================================================
     * VERIFY EVENT
     * ============================================================
     *
     * A balanced event must satisfy:
     *
     * total debits === total credits
     * ============================================================
     */

    async verifyEvent(
        eventId: string
    ): Promise<boolean> {

        const result =
            await this.db.ledgerEntry.aggregate({

                where: {
                    eventId,
                },

                _sum: {
                    amount: true,
                },

            });


        /*
         * The above total alone cannot distinguish debit from
         * credit. We therefore retrieve the entries and calculate
         * both sides.
         */

        const entries =
            await this.db.ledgerEntry.findMany({

                where: {
                    eventId,
                },

                select: {
                    amount: true,
                    direction: true,
                },

            });


        if (
            entries.length === 0
        ) {

            return false;

        }


        let totalDebits = 0;
        let totalCredits = 0;


        for (
            const entry of entries
        ) {

            const amount =
                Number(
                    entry.amount
                );


            if (
                entry.direction ===
                LedgerDirection.DEBIT
            ) {

                totalDebits +=
                    amount;

            } else {

                totalCredits +=
                    amount;

            }

        }


        return (
            totalDebits ===
            totalCredits
        );

    }


    /*
     * ============================================================
     * DASHBOARD
     * ============================================================
     *
     * This should eventually be a dedicated projection/query
     * rather than returning `any`.
     * ============================================================
     */

    async getDashboard(
        branchId: string
    ): Promise<any> {

        const entries =
            await this.db.ledgerEntry.findMany({

                where: {
                    branchId,
                },

                orderBy: {
                    createdAt: "asc",
                },

            });


        /*
         * Keep the existing dashboard shape here if your
         * frontend already depends on it.
         *
         * Replace this with your actual dashboard aggregation.
         */

        return entries.map(
            LedgerMapper.fromRow
        );

    }

}


/*
 * ================================================================
 * LEDGER MAPPER
 * ================================================================
 */

export class LedgerMapper {


    /*
     * ------------------------------------------------------------
     * DOMAIN → PRISMA
     * ------------------------------------------------------------
     */

    static toUpsertArgs(
        entry: LedgerEntry
    ): Prisma.LedgerEntryUpsertArgs {

        return {

            where: {

                eventId_index: {

                    eventId:
                        entry.eventId,

                    index:
                        entry.index,

                },

            },


            create: {

                id:
                    entry.id,

                businessId:
                    entry.businessId,

                branchId:
                    entry.branchId,

                eventId:
                    entry.eventId,

                type:
                    entry.type,

                account:
                    entry.account as Prisma.Account,

                direction:
                    entry.direction as Prisma.LedgerDirection,

                amount:
                    new Prisma.Decimal(
                        entry.amount
                    ),

                index:
                    entry.index,

                createdAt:
                    new Date(
                        entry.createdAt
                    ),

            },


            update: {

                /*
                 * Do not change the identity:
                 *
                 * id
                 * eventId
                 * index
                 *
                 * These identify the ledger line.
                 */

                type:
                    entry.type,

                account:
                    entry.account as Prisma.Account,

                direction:
                    entry.direction as Prisma.LedgerDirection,

                amount:
                    new Prisma.Decimal(
                        entry.amount
                    ),

            },

        };

    }


    /*
     * ------------------------------------------------------------
     * PRISMA → DOMAIN
     * ------------------------------------------------------------
     */

    static fromRow(
        row: PrismaLedgerEntry
    ): LedgerEntry {

        return {

            id:
                row.id,

            businessId:
                row.businessId,

            branchId:
                row.branchId,

            eventId:
                row.eventId,

            type:
                row.type,

            account:
                row.account as Account,

            direction:
                row.direction,

            amount:
                Number(
                    row.amount
                ),

            index:
                row.index,

            createdAt:
                row.createdAt.getTime(),

        };

    }

}