import {
    Account,
    LedgerEntry,
} from "@business/shared-types";
import {
  Account as PrismaAccount,
  LedgerDirection as PrismaLedgerDirection,
  LedgerEntry as PrismaLedgerEntry,
  Prisma,
} from "../../../infrastructure/postgresql/prisma/generated/client.js";
import {
    prisma,
} from "../../../infrastructure/postgresql/prismaClient.js";

import {
    LedgerRepository,
    LedgerAccountTotals,
} from "@business/ledger-engine";


export class LedgerRepositoryImpl
    implements LedgerRepository {


    constructor(
        private readonly db = prisma
    ) {}


    /*
     * ============================================================
     * APPEND
     * ============================================================
     *
     * Ledger entries are idempotent through:
     *
     * eventId + index
     *
     * Therefore use upsert rather than blind create.
     *
     * DOMAIN → DATABASE
     * ============================================================
     */

    async append(
        entries: LedgerEntry[],
        tx: Prisma.TransactionClient = this.db
    ): Promise<void> {

        for (const entry of entries) {

            await tx.ledgerEntry.upsert(
                LedgerMapper.toUpsertArgs(entry)
            );

        }

    }


    /*
     * ============================================================
     * GET BY ID
     * ============================================================
     *
     * DATABASE → DOMAIN
     * ============================================================
     */

    async getById(
        id: string
    ): Promise<LedgerEntry | null> {

        const row =
            await this.db.ledgerEntry.findUnique({

                where: {
                    id,
                },

            });


        return row
            ? LedgerMapper.fromRow(row)
            : null;

    }


    /*
     * ============================================================
     * GET BY EVENT
     * ============================================================
     *
     * eventId + index determines the ordered ledger lines
     * generated by an event.
     * ============================================================
     */

    async getByEvent(
        eventId: string
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    eventId,
                },

                orderBy: {
                    index: "asc",
                },

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET BY BUSINESS
     * ============================================================
     */

    async getByBusiness(
        businessId: string
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    businessId,
                },

                orderBy: [

                    {
                        createdAt: "asc",
                    },

                    {
                        index: "asc",
                    },

                ],

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET BY BRANCH
     * ============================================================
     */

    async getByBranch(
        branchId: string
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    branchId,
                },

                orderBy: [

                    {
                        createdAt: "asc",
                    },

                    {
                        index: "asc",
                    },

                ],

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET BY ACCOUNT
     * ============================================================
     */

    async getByAccount(
        account: Account
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {

                    account:
                        LedgerMapper.toPrismaAccount(
                            account
                        ),

                },

                orderBy: {
                    createdAt: "asc",
                },

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }


    /*
     * ============================================================
     * GET ACCOUNT TOTALS
     * ============================================================
     *
     * PostgreSQL Decimal values are converted to domain numbers
     * at the repository boundary.
     * ============================================================
     */

    async getAccountTotals(
        businessId: string,
        account: Account
    ): Promise<LedgerAccountTotals> {

        const prismaAccount =
            LedgerMapper.toPrismaAccount(
                account
            );


        const [
            debitResult,
            creditResult,
        ] = await Promise.all([

            this.db.ledgerEntry.aggregate({

                where: {

                    businessId,

                    account:
                        prismaAccount,

                    direction:
                        PrismaLedgerDirection.DEBIT,

                },

                _sum: {
                    amount: true,
                },

            }),


            this.db.ledgerEntry.aggregate({

                where: {

                    businessId,

                    account:
                        prismaAccount,

                    direction:
                        PrismaLedgerDirection.CREDIT,

                },

                _sum: {
                    amount: true,
                },

            }),

        ]);


        return {

            totalDebits:
                Number(
                    debitResult._sum.amount ?? 0
                ),

            totalCredits:
                Number(
                    creditResult._sum.amount ?? 0
                ),

        };

    }


    /*
     * ============================================================
     * VERIFY EVENT
     * ============================================================
     *
     * A balanced double-entry event must satisfy:
     *
     * total debits = total credits
     *
     * IMPORTANT:
     * Do not compare JavaScript floating-point totals directly
     * for financial correctness.
     *
     * We use Decimal arithmetic here.
     * ============================================================
     */

    async verifyEvent(
        eventId: string
    ): Promise<boolean> {

        const entries =
            await this.db.ledgerEntry.findMany({

                where: {
                    eventId,
                },

                select: {

                    amount: true,

                    direction: true,

                },

            });


        if (
            entries.length === 0
        ) {

            return false;

        }


        let totalDebits =
            new Prisma.Decimal(0);

        let totalCredits =
            new Prisma.Decimal(0);


        for (
            const entry of entries
        ) {

            if (
                entry.direction ===
                PrismaLedgerDirection.DEBIT
            ) {

                totalDebits =
                    totalDebits.plus(
                        entry.amount
                    );

            } else {

                totalCredits =
                    totalCredits.plus(
                        entry.amount
                    );

            }

        }


        return totalDebits.equals(
            totalCredits
        );

    }


    /*
     * ============================================================
     * DASHBOARD
     * ============================================================
     *
     * Returns domain LedgerEntry values rather than Prisma rows.
     *
     * Eventually this should become a dedicated projection/query
     * model rather than returning raw ledger entries.
     * ============================================================
     */

    async getDashboard(
        branchId: string
    ): Promise<LedgerEntry[]> {

        const rows =
            await this.db.ledgerEntry.findMany({

                where: {
                    branchId,
                },

                orderBy: {
                    createdAt: "asc",
                },

            });


        return rows.map(
            LedgerMapper.fromRow
        );

    }

}


/*
 * ================================================================
 * LEDGER MAPPER
 * ================================================================
 *
 * DOMAIN
 *
 * LedgerEntry
 *   amount: number
 *   createdAt: number
 *   account: Account
 *   direction: "DEBIT" | "CREDIT"
 *
 *              ↕
 *
 * DATABASE
 *
 * PrismaLedgerEntry
 *   amount: Decimal
 *   createdAt: Date
 *   account: Prisma.Account
 *   direction: Prisma.LedgerDirection
 *
 * ================================================================
 */

export class LedgerMapper {


    /*
     * ============================================================
     * ACCOUNT → PRISMA ACCOUNT
     * ============================================================
     */

    static toPrismaAccount(
        account: Account
    ): PrismaAccount {

        return account as PrismaAccount;

    }


    /*
     * ============================================================
     * DIRECTION → PRISMA ENUM
     * ============================================================
     */

    static toPrismaDirection(
        direction: LedgerEntry["direction"]
    ): PrismaLedgerDirection{

        return direction as PrismaLedgerDirection;

    }


    /*
     * ============================================================
     * DOMAIN → PRISMA UPSERT
     * ============================================================
     */

    static toUpsertArgs(
        entry: LedgerEntry
    ): Prisma.LedgerEntryUpsertArgs {

        return {

            /*
             * Identity:
             *
             * eventId + index
             */

            where: {

                eventId_index: {

                    eventId:
                        entry.eventId,

                    index:
                        entry.index,

                },

            },


            /*
             * ----------------------------------------------------
             * CREATE
             * ----------------------------------------------------
             */

            create: {

                id:
                    entry.id,

                businessId:
                    entry.businessId,

                branchId:
                    entry.branchId,

                eventId:
                    entry.eventId,

                type:
                    entry.type,

                account:
                    this.toPrismaAccount(
                        entry.account
                    ),

                direction:
                    this.toPrismaDirection(
                        entry.direction
                    ),

                amount:
                    new Prisma.Decimal(
                        entry.amount
                    ),

                index:
                    entry.index,

                createdAt:
                    new Date(
                        entry.createdAt
                    ),

            },


            /*
             * ----------------------------------------------------
             * UPDATE
             * ----------------------------------------------------
             *
             * Identity fields are intentionally not modified.
             * ----------------------------------------------------
             */

            update: {

                type:
                    entry.type,

                account:
                    this.toPrismaAccount(
                        entry.account
                    ),

                direction:
                    this.toPrismaDirection(
                        entry.direction
                    ),

                amount:
                    new Prisma.Decimal(
                        entry.amount
                    ),

            },

        };

    }


    /*
     * ============================================================
     * PRISMA → DOMAIN
     * ============================================================
     *
     * Decimal → number
     * Date    → Unix milliseconds
     * ============================================================
     */

    static fromRow(
        row: PrismaLedgerEntry
    ): LedgerEntry {

        return {

            id:
                row.id,

            businessId:
                row.businessId,

            branchId:
                row.branchId,

            eventId:
                row.eventId,

            type:
                row.type,

            account:
                row.account as Account,

            direction:
                row.direction as LedgerEntry["direction"],

            amount:
                Number(
                    row.amount
                ),

            index:
                row.index,

            createdAt:
                row.createdAt.getTime(),

        };

    }

}