export enum AggregateType {
  BUSINESS = "BUSINESS",
  BRANCH = "BRANCH",

  PRODUCT = "PRODUCT",
  INVENTORY = "INVENTORY",

  ASSET = "ASSET",
  LIABILITY = "LIABILITY",

  CAPITAL_ACCOUNT = "CAPITAL_ACCOUNT",

  SALE = "SALE",
  EXPENSE = "EXPENSE",
}