export enum SyncErrorCode {

  UNKNOWN = "UNKNOWN",

  VALIDATION = "VALIDATION",

  VERSION_CONFLICT = "VERSION_CONFLICT",

  BUSINESS_RULE = "BUSINESS_RULE",

  DUPLICATE_EVENT = "DUPLICATE_EVENT",

  EVENT_TOO_OLD = "EVENT_TOO_OLD",

  EVENT_TOO_NEW = "EVENT_TOO_NEW",

  AGGREGATE_NOT_FOUND = "AGGREGATE_NOT_FOUND",

  NETWORK = "NETWORK",

  SERVER = "SERVER",

  AUTHENTICATION = "AUTHENTICATION"

}