export const financeEventType = {
    ASSET_ADDED: "ASSET_ADDED",
    ASSET_DISPOSED: "ASSET_DISPOSED",
    EXPENSES_ADDED: "EXPENSES_ADDED",
    LIABILITY_ADDED: "LIABILITY_ADDED",
    LIABILITY_REPAYMENT: "LIABILITY_REPAYMENT",
    CASH_ADDED: "CASH_ADDED",
    CAPITAL_INJECTION: "CAPITAL_INJECTION",
    CAPITAL_DRAWINGS: "CAPITAL_WITHDRAWAL",

    //Branch-Transfer
    BRANCH_TRANSFER_OUT: "BRANCH_TRANSFER_OUT",
    BRANCH_TRANSFER_IN: "BRANCH_TRANSFER_IN"
}